server:
  servlet:
    context-path: /api/v1
  port: 8089

spring:
  datasource:
    url: jdbc:sqlserver://149.56.143.19;databaseName=PolizasCoppel
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: Coppel1234 
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8;
    hikari:
      minimumIdle: 4
      maximumPoolSize: 8
      idleTimeout: 15000
      poolName: SpringBootJPAHikariCP
      maxLifetime: 1800000
      connectionTimeout: 30000
  sql:
    init:
      encoding: UTF-8
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
